version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - mynet
  chatsocket:
    build:
      context: ./chatsocket
    ports:
      - "9000:9000"
    volumes:
      - ./chatsocket:/app
    command: npm start
    networks:
      - mynet
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start
    networks:
      - mynet


networks:
  mynet:
    driver: bridge