# Generated by Django 4.1.5 on 2023-02-22 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_listing_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewee",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
