# Generated by Django 4.1.5 on 2023-01-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_listing_user_review_listing_owner_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="sale_or_rent",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
