# Generated by Django 4.1.5 on 2023-01-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
