# Generated by Django 4.1.5 on 2023-03-02 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_listing_buyer_left_review_listing_seller_left_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="town",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
