# Generated by Django 4.1.5 on 2023-01-29 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_userpurchases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpurchases",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_listing",
                to="main.listing",
            ),
        ),
        migrations.AlterField(
            model_name="userpurchases",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
