# Generated by Django 4.1.5 on 2023-02-18 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_message_isofferandpending"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="timeCreated",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
