# Generated by Django 4.1.5 on 2023-02-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_chat_timecreated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="offer",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="message",
            name="isOffer",
        ),
        migrations.RemoveField(
            model_name="message",
            name="isOfferAndAccepted",
        ),
        migrations.RemoveField(
            model_name="message",
            name="isOfferAndDeclined",
        ),
        migrations.RemoveField(
            model_name="message",
            name="isOfferAndPending",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="is_accepted",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="is_declined",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="is_pending",
        ),
        migrations.AddField(
            model_name="chat",
            name="offers",
            field=models.ManyToManyField(blank=True, to="main.offer"),
        ),
    ]
