# Generated by Django 4.1.5 on 2023-02-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_rename_offer_offer_price_remove_message_isoffer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
